### ISSUE TITLE
Drawing arrows/circles at the starting position of a board (or a board that just shows a custom position) is broken

### ISSUE THREAD

**Issue by rmogstad** [mliebelt/PgnViewerJS#443] opened 2023-05-08 23:33 UTC
When trying to draw arrows or circles when there is no current "move" (e.g. in the starting position, on the starting position when hideMovesBefore is set, when a board just shows a static position), the board draws double arrows and requires that you right-click twice.  It's not very easy to describe all of the symptoms, but it is pretty easy to reproduce.

Console error is:

caught TypeError: Cannot read properties of undefined (reading 'commentDiag')
    at M.PgnReader.setShapes (index.umd.js:11352:20)
    at Object.onChange (pgnv.ts:642:32)
    at zM (draw.js:84:18)
    at draw.js:80:5
    at iM (draw.js:50:13)
    at HTMLDocument.<anonymous> (events.js:70:17)
s

**Comment by mliebelt** [comment] 2023-05-09 17:58
Seems to be a duplicate of #338 I will have a look at it.

**Comment by rmogstad** [comment] 2023-05-09 18:54
If you say so.  I can see how fixing one would fix the other.

**Comment by mliebelt** [comment] 2023-05-10 09:41
Checked it, it seems that the parser is not able (any more) to read it. I will investigate, hopefully the fix will be simple.

**Comment by mliebelt** [comment] 2023-05-10 11:18
Ok, next step. I have an example, I can reproduce the error (somehow). What I see all the time:

* On first display, the arrows are shown at the wrong location. Seems to be a rendering problem ...
* Having played one move forth, and one back fixes the problem.
* This is of course not possible when only showing a position (no moves in the configuration).
* I see that for Chromium-based browsers: Chrome, Chromium, Vivaldi.
* I don't see it on Firefox.

**Comment by mliebelt** [comment] 2023-05-10 12:49
I think I have found a solution, but want to have more test cases added to ensure that it works in different circumstances. And I would like to add some more bug fixes to the next release.

**Comment by mliebelt** [comment] 2023-05-10 14:12
Ok, added some more examples:

* pgnEdit is working the same
* pgnBoard is not working (no idea, why). So this has to be debugged then.

**Closed** 2023-05-14 15:25 UTC
