### ISSUE TITLE
Facing this error when starting turn is changed to BLACK through position param

### ISSUE THREAD

**Issue by coffeeDev98** [mliebelt/PgnViewerJS#354] opened 2022-02-23 04:10 UTC
Having an issue when changing the start turn to BLACK. 
Example FEN: rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR b KQkq - 0 1

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63295908/155260306-b416c9e3-4cd5-43fa-976e-b9d25eda8a26.png">

**Comment by mliebelt** [comment] 2022-02-23 06:10
Try to understand your issue, but I fail with it. Could you do the following:

* Describe the steps you did to produce the example, if possible, give the code, where the `pgnXX` function is called.
* Which version are you using? I did a lot of refactoring lately, so I want to be sure to debug something that is in the current published version.

I have tried to reproduce your error. What I have understood is, that you take the start position, but you want black to start the game. I did the following:

1. Went to the configuration builder: https://mliebelt.github.io/PgnViewerJS/config/config.html
1. Switched there the mode to edit (so I am able to do moves).
2. Entered the FEN "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR b KQkq - 0 1" into the FEN field.
3. Went to the board, and made the first move with black. This worked.
4. When I then tried to do the first move with white, I could not.
5. I opened the developer console, and saw a similar error to yours.

Is that the scenario we are talking about?

I have identified the place, where the error happens, and could fix it (by using `?` as the only change).

![image](https://user-images.githubusercontent.com/520039/155269429-05c2e97b-eae0-4da0-90f6-5c5fd6d38ed6.png)

At the moment, I don't want to create a new version of pgn-viewer, because I expect there other errors have been introduced by  myself during refactoring, going from Javascript to Typescript. I have I can do that in a few days, perhaps the next weekend.

**Comment by coffeeDev98** [comment] 2022-02-23 06:17
Yes, It is the same error I've mentioned above. Even if the black move is played, PGN is not recorded and following moves cannot be played.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63295908/155270127-2ea01d53-62ed-4d9a-b650-c90377f7e4ad.png">

**Comment by mliebelt** [comment] 2022-02-24 05:58
The commit linked is the fix for this problem. I close it now, and will see when it will be part of a new version then. There will be a hint / comment about that then.

**Closed by mliebelt** 2022-02-24 05:58 UTC
Labels: bug

**Comment by mliebelt** [comment] 2022-02-26 16:15
I created a new release 1.5.14, you should try to upgrade, and hopefully the error is not there any more. I just checked it on the configuration builder that is online. Just published to npm as well.

**Comment by coffeeDev98** [comment] 2022-03-07 13:29
Tried to install the new release. Facing some issues 
`Packing chessground@https://github.com/mliebelt/Chessground.git#commit=2043d46eea121cfa8c6a6b84897bc98b5d74950c from sources
Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile

➤ YN0000: Downloading https://nightly.yarnpkg.com/latest.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-1.23.0-20220130.1630.cjs
➤ YN0000: Done in 0s 478ms

yarn install v1.23.0-20220130.1630
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ $npm_execpath run compile
Internal Error: chessground@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at gS.getCandidates (/Users/user/Desktop/betterEd/better-class/.yarn/releases/yarn-sources.cjs:285:4265)
    at lc.getCandidates (/Users/user/Desktop/betterEd/better-class/.yarn/releases/yarn-sources.cjs:281:4819)
    at /Users/user/Desktop/betterEd/better-class/.yarn/releases/yarn-sources.cjs:295:7544
    at Object.prettifyAsyncErrors (/Users/user/Desktop/betterEd/better-class/.yarn/releases/yarn-sources.cjs:10:30361)
    at D (/Users/user/Desktop/betterEd/better-class/.yarn/releases/yarn-sources.cjs:295:7507)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`

**Comment by coffeeDev98** [comment] 2022-03-07 13:33
Doesn't happen with the other versions though...

**Comment by coffeeDev98** [comment] 2022-03-08 06:34
I'm using typescript version ^4.2.3

**Comment by coffeeDev98** [comment] 2022-03-08 07:32
I get the following error when trying to install
```
➤ YN0058: │ chessground@https://github.com/mliebelt/Chessground.git#commit=2043d46eea121cfa8c6a6b84897bc98b5d74950c: Packing the package failed (exit code 1, logs can be found here: /private/var/folders/fx/1gzks4s56z993h86h1sqvcjw0000gn/T/xfs-b12d9b06/pack.log)

```

**Comment by mliebelt** [comment] 2022-03-08 12:47
Sorry, it is really difficult to diagnose anything, because there are only snippets available. So again, do you have a public reference to the project that you are trying to do? Any reference, where I can find something? What did you do to provoke the error? When I use my fork of Chessground, no build at all is triggered (and no, it is not necessary, you can use it right from the sources).

**Comment by mliebelt** [comment] 2022-03-08 12:55
I tried it again. This  is what I did:

1. Copy the current state of the complete repository to a local directory.
2. Go the root directory (of that zip file), and start `npm install`.
3. Go to `modules/pgn-reader`, and start there `npm install`.
4. Go to `modules/pgn-viewer`, and start there `npm install`.

This works for me, no error. What you could do

1. Repeat what I did, in the same order.
2. Write down everything you do, get as result, ... that is not obvious.
3. Go to your clone of [`PgnViewerJS`](https://github.com/coffeeDev98/PgnViewerJS), and enable there issues.
4. Create a new ticket, and provide exactly how to get the wrong behavior from above.

The reasons for that are:
* You have an older state of the repository (something like 20 commits behind). I don't debug old state ...
* You cannot show anything publicly, that allows others (me) to re-create that problem.

Sorry, sound unpolite, but we are now discussing for many days (in a closed ticket) something completely unrelated. Please, follow my advise here.

**Comment by coffeeDev98** [comment] 2022-03-08 13:26
No no, I understand. It's not unpolite. Sorry for dragging this discussion. 

Did some testing with `yarn` and noticed the issue occurs in yarn versions above `1.23.x`.
I'm currently on yarn `v2.4.0`

But you can reproduce this issue with yarn `v3.2.0`

**Comment by mliebelt** [comment] 2022-03-08 14:13
I cannot. Please follow my advise ...
