### ISSUE TITLE
Piece move glitch when clicking 'next move' rapidly

### ISSUE THREAD

**Issue by xeyownt** [mliebelt/PgnViewerJS#69] opened 2017-12-23 12:21 UTC
In `view` mode (and probably `edit` mode as well), there is a piece move glitch when clicking rapidly on `next` or `previous` button. The glitch is that the piece appears duplicated on the board: first as the moving piece, that moves to target square, and second as a piece already occupying the target square.

To trigger the glitch, one must click on the 'next' or 'previous' button before the current move completes. In that case, we can see that the next piece to move appears on its target square before this next move completes.

![image](https://user-images.githubusercontent.com/16546024/34319490-017fae3e-e7e4-11e7-8f7f-a37071fbe38b.png)

**Comment by mliebelt** [comment] 2017-12-25 10:49
Will look at this, if I can reproduce it. Should have to do with moving pieces during one move is not finished. The easiest solution would be to block pressing move buttons as long as a move is executed.

**Comment by mliebelt** [comment] 2017-12-27 11:08
I was not able to reproduce the problem with different browser, so skip it for the current release.

**Comment by xeyownt** [comment] 2017-12-27 14:24
For info, I have it on Ubuntu Firefox 56.0 and Chromium 63, for instance on example http://mliebelt.github.io/PgnViewerJS/docu/examples.html#1050.

But in any case this is a minor issue, and not sure it's worth a fix. In any case, allowing fast clicking is maybe more user friendly.

**Comment by mliebelt** [comment] 2018-05-21 11:02
I was not able to reproduce it, and I have switched implementation of the chessboard to Chessground in the meanwhile. So I will keep it open up to the new (forthcoming)  release, and if I don't get any feedback on this issue, I will close it.

**Closed** 2020-05-01 11:54 UTC
Labels: bug
